name: gestao_de_estagio
description: "Aplicativo Flutter para gestão de estudantes e supervisores com Clean Architecture e BLoC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  
  # Dependency Injection
  flutter_modular: ^6.4.1
  
  # Supabase
  supabase_flutter: ^2.9.1
  
  # UI Components
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  
  # Charts and Data Visualization
  fl_chart: ^0.66.2
  
  # Utils
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  provider: ^6.0.5
  url_launcher: ^6.2.5
  
  # File Management and Sharing
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  
  # Validation
  formz: ^0.7.0
  
  # Network
  dio: ^5.4.3+1
  
  # Push Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.2.0
  
  # Offline Support
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  
  # Local Storage - Removido temporariamente para resolver conflitos
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  
  # Logging
  logger: ^2.6.0
  postgrest: ^2.4.2
  flutter_dotenv: ^5.1.0
  # shared_preferences_linux: ^2.4.1  # Temporariamente removido para resolver conflitos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  
  # Code Generation
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env
