name: gestao_de_estagio
description: "Sistema de Gestão de Estágio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.1
  equatable: ^2.0.5
  
  # Dependency Injection
  flutter_modular: ^6.3.2
  
  # Supabase
  supabase_flutter: ^2.0.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Forms & Validation
  formz: ^0.6.1
  
  # UI & Theming
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  lottie: ^3.1.2
  
  # Charts & Visualization
  fl_chart: ^0.66.2
  
  # File & Storage
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  path: ^1.8.3
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.2.0
  
  # Environment & Config
  flutter_dotenv: ^5.1.0
  
  # Production Monitoring & Analytics
  firebase_performance: ^0.9.3+6
  sentry_flutter: ^7.14.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  
  # Logging
  logger: ^2.6.0
  postgrest: ^2.4.2
  
  # Utils
  intl: ^0.20.2
  provider: ^6.0.5
  url_launcher: ^6.2.5
  
  # Offline Support
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env
