// Mocks generated by Mockito 5.4.6 from annotations
// in gestao_de_estagio/test/domain/usecases/auth/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gestao_de_estagio/core/enums/class_shift.dart' as _i8;
import 'package:gestao_de_estagio/core/enums/internship_shift.dart' as _i9;
import 'package:gestao_de_estagio/core/enums/user_role.dart' as _i7;
import 'package:gestao_de_estagio/core/errors/app_exceptions.dart' as _i5;
import 'package:gestao_de_estagio/domain/entities/user_entity.dart' as _i6;
import 'package:gestao_de_estagio/domain/repositories/i_auth_repository.dart'
    as _i3;
import 'package:gestao_de_estagio/domain/usecases/auth/update_profile_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.UserEntity>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, void>>.value(
            _FakeEither_0<_i5.AppFailure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>> register({
    required String? fullName,
    required String? email,
    required String? password,
    required _i7.UserRole? role,
    String? registration,
    bool? isMandatoryInternship,
    String? supervisorId,
    String? course,
    String? advisorName,
    _i8.ClassShift? classShift,
    _i9.InternshipShift? internshipShift,
    DateTime? birthDate,
    DateTime? contractStartDate,
    DateTime? contractEndDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #email: email,
            #password: password,
            #role: role,
            #registration: registration,
            #isMandatoryInternship: isMandatoryInternship,
            #supervisorId: supervisorId,
            #course: course,
            #advisorName: advisorName,
            #classShift: classShift,
            #internshipShift: internshipShift,
            #birthDate: birthDate,
            #contractStartDate: contractStartDate,
            #contractEndDate: contractEndDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #fullName: fullName,
              #email: email,
              #password: password,
              #role: role,
              #registration: registration,
              #isMandatoryInternship: isMandatoryInternship,
              #supervisorId: supervisorId,
              #course: course,
              #advisorName: advisorName,
              #classShift: classShift,
              #internshipShift: internshipShift,
              #birthDate: birthDate,
              #contractStartDate: contractStartDate,
              #contractEndDate: contractEndDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity?>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.UserEntity?>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity?>>);

  @override
  _i4.Stream<_i6.UserEntity?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i4.Stream<_i6.UserEntity?>.empty(),
      ) as _i4.Stream<_i6.UserEntity?>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>> updateProfile(
          {required _i10.UpdateProfileParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, void>> resetPassword(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, void>>.value(
            _FakeEither_0<_i5.AppFailure, void>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, void>>);

  @override
  _i4.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
