// Mocks generated by Mockito 5.4.6 from annotations
// in gestao_de_estagio/test/domain/usecases/time_log/clock_in_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gestao_de_estagio/core/errors/app_exceptions.dart' as _i5;
import 'package:gestao_de_estagio/domain/entities/time_log_entity.dart' as _i6;
import 'package:gestao_de_estagio/domain/repositories/i_time_log_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITimeLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITimeLogRepository extends _i1.Mock
    implements _i3.ITimeLogRepository {
  MockITimeLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>
      getTimeLogsByStudent(String? studentId) => (super.noSuchMethod(
            Invocation.method(
              #getTimeLogsByStudent,
              [studentId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>.value(
                _FakeEither_0<_i5.AppFailure, List<_i6.TimeLogEntity>>(
              this,
              Invocation.method(
                #getTimeLogsByStudent,
                [studentId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity?>> getActiveTimeLog(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTimeLog,
          [studentId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity?>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity?>(
          this,
          Invocation.method(
            #getActiveTimeLog,
            [studentId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>> clockIn(
    String? studentId, {
    String? description,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clockIn,
          [studentId],
          {
            #description: description,
            #notes: notes,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
          this,
          Invocation.method(
            #clockIn,
            [studentId],
            {
              #description: description,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>> clockOut(
    String? timeLogId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clockOut,
          [timeLogId],
          {#notes: notes},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
          this,
          Invocation.method(
            #clockOut,
            [timeLogId],
            {#notes: notes},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>> createTimeLog(
          _i6.TimeLogEntity? timeLog) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTimeLog,
          [timeLog],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
          this,
          Invocation.method(
            #createTimeLog,
            [timeLog],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>> updateTimeLog(
          _i6.TimeLogEntity? timeLog) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTimeLog,
          [timeLog],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
          this,
          Invocation.method(
            #updateTimeLog,
            [timeLog],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, void>> deleteTimeLog(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTimeLog,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, void>>.value(
            _FakeEither_0<_i5.AppFailure, void>(
          this,
          Invocation.method(
            #deleteTimeLog,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.AppFailure, Map<String, dynamic>>> getTotalHoursByStudent(
    String? studentId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByStudent,
          [
            studentId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.AppFailure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getTotalHoursByStudent,
            [
              studentId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, Duration>> getTotalHoursByPeriod(
    String? studentId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByPeriod,
          [
            studentId,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, Duration>>.value(
            _FakeEither_0<_i5.AppFailure, Duration>(
          this,
          Invocation.method(
            #getTotalHoursByPeriod,
            [
              studentId,
              start,
              end,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, Duration>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>> getTimeLogById(
          String? timeLogId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeLogById,
          [timeLogId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
          this,
          Invocation.method(
            #getTimeLogById,
            [timeLogId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>
      updateTimeLogStatus({
    required String? timeLogId,
    required bool? approved,
    String? rejectionReason,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateTimeLogStatus,
              [],
              {
                #timeLogId: timeLogId,
                #approved: approved,
                #rejectionReason: rejectionReason,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>.value(
                    _FakeEither_0<_i5.AppFailure, _i6.TimeLogEntity>(
              this,
              Invocation.method(
                #updateTimeLogStatus,
                [],
                {
                  #timeLogId: timeLogId,
                  #approved: approved,
                  #rejectionReason: rejectionReason,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.TimeLogEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>
      getTimeLogsBySupervisor(String? supervisorId) => (super.noSuchMethod(
            Invocation.method(
              #getTimeLogsBySupervisor,
              [supervisorId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>.value(
                _FakeEither_0<_i5.AppFailure, List<_i6.TimeLogEntity>>(
              this,
              Invocation.method(
                #getTimeLogsBySupervisor,
                [supervisorId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>
      getTimeLogsByDateRange({
    required String? studentId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTimeLogsByDateRange,
              [],
              {
                #studentId: studentId,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>.value(
                _FakeEither_0<_i5.AppFailure, List<_i6.TimeLogEntity>>(
              this,
              Invocation.method(
                #getTimeLogsByDateRange,
                [],
                {
                  #studentId: studentId,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppFailure, List<_i6.TimeLogEntity>>>);
}
