// Mocks generated by Mockito 5.4.6 from annotations
// in gestao_de_estagio/test/data/repositories/time_log_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gestao_de_estagio/data/datasources/supabase/time_log_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimeLogDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeLogDatasource extends _i1.Mock implements _i2.TimeLogDatasource {
  MockTimeLogDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllTimeLogs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTimeLogs,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getTimeLogById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeLogById,
          [id],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTimeLogsByStudent(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeLogsByStudent,
          [studentId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTimeLogsByDateRange(
    String? studentId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeLogsByDateRange,
          [
            studentId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getActiveTimeLog(String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTimeLog,
          [studentId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>> createTimeLog(
          Map<String, dynamic>? timeLogData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTimeLog,
          [timeLogData],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> deleteTimeLog(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTimeLog,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> clockIn(
    String? studentId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clockIn,
          [studentId],
          {#notes: notes},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> clockOut(
    String? studentId, {
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clockOut,
          [studentId],
          {#notes: notes},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Duration> getTotalHoursByPeriod(
    String? studentId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByPeriod,
          [
            studentId,
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<Duration>.value(_FakeDuration_0(
          this,
          Invocation.method(
            #getTotalHoursByPeriod,
            [
              studentId,
              start,
              end,
            ],
          ),
        )),
      ) as _i3.Future<Duration>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPendingTimeLogs(
          String? supervisorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingTimeLogs,
          [supervisorId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> updateTimeLog(
    String? id,
    Map<String, dynamic>? timeLogData, {
    String? rejectionReason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTimeLog,
          [
            id,
            timeLogData,
          ],
          {#rejectionReason: rejectionReason},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateTimeLogData(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTimeLogData,
          [
            id,
            data,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getTotalHoursByStudent(
    String? studentId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalHoursByStudent,
          [
            studentId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getTimeLogsBySupervisor(
          String? supervisorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeLogsBySupervisor,
          [supervisorId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}
