name: Deploy Flutter Web to Netlify

on:
  push:
    branches:
      - main
      - desenvolvimento
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Flutter Web (release)
        run: flutter build web --release

      - name: Install Netlify CLI
        run: |
          npm i -g netlify-cli@17
          netlify --version

      - name: Deploy to Netlify (Production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          if [ -z "$NETLIFY_AUTH_TOKEN" ] || [ -z "$NETLIFY_SITE_ID" ]; then
            echo "Missing NETLIFY_AUTH_TOKEN or NETLIFY_SITE_ID secrets" >&2
            exit 1
          fi
          netlify deploy --dir=build/web --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
