name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [ desenvolvimento, main ]
  pull_request:
    branches: [ desenvolvimento, main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5.0'

      - name: Instalar dependências
        run: flutter pub get

      - name: Rodar testes
        run: flutter test

      - name: Build IPA release
        run: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          for app in *.app; do
            /usr/bin/xcrun -sdk iphoneos PackageApplication -v "$app" -o "../../ipa/${app%.app}.ipa";
          done

      - name: Upload IPA como artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-release-ipa
          path: build/ios/ipa/*.ipa 