name: Flutter Android CI/CD Google Play

on:
  push:
    branches: [ main, desenvolvimento ]
  pull_request:
    branches: [ main, desenvolvimento ]

jobs:
  build-deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Set up Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Deploy to Google Play (Fastlane)
        env:
          SUPPLY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          cd android
          echo "$SUPPLY_JSON_KEY" > fastlane.json
          fastlane supply --json_key fastlane.json --package_name com.seupacote.seuapp --apk ../build/app/outputs/flutter-apk/app-release.apk --track internal
          fastlane supply init

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/*.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }} 